config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq" # mount Sidekiq::Web in your Rails app
  
  resources :contacts_files, only: [ :show, :create, :index] do 
    member do 
      post '/import', to: 'contacts_files#import_contacts_from_file'
    end
  end
  
  devise_for :users
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user
  VALID_NAME_REGEX = /[a-zA-Z0-9\-]/
  validates :name, presence: true,
                    format: { with: VALID_NAME_REGEX }
  VALID_PHONE_NUMBER_REGEX = /\(\+\d{2,3}\) \d{3}(?: \d{3} \d{2} \d{2}|\-\d{3}\-\d{2}\-\d{2})/
  validates :phone_number, presence: true,
                            format: { with: VALID_PHONE_NUMBER_REGEX }
  validates :address, presence: true, allow_blank: false
  validates :cc_mask, presence: true, credit_card_number: true, on: :create
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, 
                      format: { with: VALID_EMAIL_REGEX }
  validates_uniqueness_of :email, scope: :user_id

  after_validation :set_credit_card_info

  private

  def set_credit_card_info
    detector = CreditCardValidations::Detector.new(cc_mask)
    self.cc_franchise = detector.brand
    self.hashed_cc = Digest::SHA256.base64digest cc_mask
    self.cc_mask = cc_mask.chars.last(4).join("")
  end
end

app/models/contacts_file.rb
class ContactsFile < ApplicationRecord
  validates :name, presence: true
  belongs_to :user
  has_many :import_failures
  has_one_attached :csv_file

  enum status: { pending: 'ON HOLD',
                  processing: 'PROCESSING',
                  failed: 'FAILED',
                  finished: 'TERMINATED'
  }

  before_create :init_status

  HEADER_COLUMNS = %i[name birthdate phone_number address email cc_mask].freeze

  private
  def init_status
    self.status = ContactsFile.statuses[:pending]
    self.imports = 0
  end
end

app/models/import_failure.rb
class ImportFailure < ApplicationRecord
  belongs_to :contacts_file
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable
  has_many :contacts
  has_many :contacts_files
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    def index
    end
end

app/controllers/contacts_files_controller.rb
require 'csv'

class ContactsFilesController < ApplicationController
  before_action :set_contacts_file, only: [:show, :import_contacts_from_file]
  def index
    @contacts_file = ContactsFile.new
    @contacts_files = current_user.contacts_files.paginate(page: params[:page], per_page: 5)
  end

  def show
    
  end

  def create
    params_hash = contacts_file_params
    @contacts_file = ContactsFile.new(params_hash)
    @contacts_file.user = current_user
    @contacts_file.name = params_hash.to_h[:csv_file].original_filename
    if(@contacts_file.save)
      redirect_to @contacts_file
    else 
      render :index
    end
  end

  def import_contacts_from_file
    # if @contacts_file.pending?
    #   @contacts_file.processing!
    #   CSV.parse(@contacts_file.csv_file.download, headers: true, encoding: 'UTF-8') do |file_line|
    #     new_contact = current_user.contacts.build(file_line.to_h)
    #     if new_contact.save 
    #       @contacts_file.imports += 1
    #     else
    #       @contacts_file.import_failures.build(file_line: file_line.to_s, failure_messages: new_contact.errors.full_messages.join("\n"))
    #     end
    #     rescue ActiveModel::UnknownAttributeError => e 
    #       @contacts_file.import_failures.build(file_line: file_line.to_s, failure_messages: e.message)
    #       next
    #   end
    #   if @contacts_file.imports == 0
    #     @contacts_file.failed!
    #   else
    #     @contacts_file.finished!
    #   end
    # end
    ContactImportWorker.perform_async(@contacts_file.id)
    redirect_to @contacts_file
  end

  private
  def contacts_file_params
    params.require(:contacts_file).permit(:csv_file)
  end

  def set_contacts_file
    @contacts_file = current_user.contacts_files.find_by(id: params[:id])
    redirect_to contacts_files_url if @contacts_file.nil?
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index
        @contacts = current_user.contacts.paginate(page: params[:page], per_page: 10)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_files_helper.rb
module ContactsFilesHelper
end

app/views/contacts_files/_errors.html.erb
<% if @contacts_file.import_failures.any? %>
<h1> The following errors were found while importing records from file </h1>
  <table class="table">
    <thead>
      <tr>
        <th scope="col"> Input line </th>
        <th scope="col"> Error messages</th>
      </tr>
    </thead>
    <tbody>
      <% @contacts_file.import_failures.each do |import_failure| %>
        <tr>
          <td> <%= import_failure.file_line %> </td>
          <td> <%= import_failure.failure_messages %> </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/contacts_files/_form.html.erb
<div class="container">
  <h1> Import a new file </h1>
  <%= form_with(model: @contacts_file, url: url_for(controller: 'contacts_files', action: 'create'), local: true) do |form| %>
      <div class="form-group">
        <div class="custom-file">
          <%= form.file_field :csv_file, class:"custom-file-input" %>
          <%= form.label :csv_file, class:"custom-file-label" %>
        </div>
      </div>
      <div class="form-group row justify-content-center">
        <%= form.submit class: "btn btn-primary" %>
      </div>
  <% end %>
</div>

app/views/contacts_files/index.html.erb
<%= link_to "Back to contacts", root_path, class: "btn btn-primary"%>
<br/>
<table class="table">
  <thead>
    <tr>
      <th scope="col"> ID </th>
      <th scope="col"> File name</th>
      <th scope="col"> Status</th>
      <th scope="col"> Imported Records</th>
      <th scope="col"> Failed Records</th>
      <th scope="col"> Actions </th>
    </tr>
  </thead>
  <tbody>
    <% @contacts_files.each do |cf| %>
        <tr>
            <td> <%= cf.id %> </td>
            <td> <%= cf.name %> </td>
            <td> <%= cf.status %> </td>
            <td> <%= cf.imports %> </td>
            <td> <%= cf.import_failures.any? ? cf.import_failures.count : 0%></td>
            <td> 
                <%= link_to "Show", contacts_file_path(cf), class: "btn btn-success" %> 
                <%= link_to "Import", import_contacts_file_path(cf), method: :post, class: "btn btn-warning" %>
            </td>
        </tr>
    <% end %>
  </tbody>
</table>

  <div class="flickr_pagination">
    <%= will_paginate @contacts_files, :container => false %>
  </div>
<%= render 'form', contacts_file: @contacts_file %>

app/views/contacts_files/show.html.erb
<h1> File name: <%= @contacts_file.name %> </h1>
<p> Import status: <%= @contacts_file.status%></p>
<% if @contacts_file.pending? %>
  <h1> The import process has not begun yet </h1>
<% end %>
<% if @contacts_file.processing? %>
  <h1> The file is being processed </h1>
<% end %>
<% if @contacts_file.finished? %>
  <h1> The import process finished and <%= @contacts_file.imports %> <%= @contacts_file.imports == 1 ? "record has " : "records have "%> been imported </h1>
  <%= render 'errors', contacts_file: @contacts_file %>
<% end %>
<% if @contacts_file.failed? %>
  <h1> The import process finished and no records have been imported </h1>
  <%= render 'errors', contacts_file: @contacts_file %>
<% end %>

<%= link_to "Back to all imports", contacts_files_path, class: "btn btn-primary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ContactManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Contacts Manager</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          
          <form class="d-flex">
            <% if user_signed_in? %>
              <%= link_to("Logout", destroy_user_session_path,
                            class: "btn btn-danger logout-button", method: :delete)%>
            <% end %>
          </form>
        </div>
      </div>
    </nav>
    <div class="container">
      <p class="notice"> <%= notice %> </p>
      <p class="alert"> <%= alert %> </p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/welcome/index.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Phone number</th>
      <th scope="col">Birthdate</th>
      <th scope="col">Address</th>
      <th scope="col">Email</th>
      <th scope="col">Credit Card Franchise</th>
      <th scope="col">Credit card mask</th>
    </tr>
  </thead>
  <tbody>
    <% @contacts.each do |contact|%>
        <tr>
            <td> <%= contact.name %> </td>
            <td> <%= contact.phone_number %> </td>
            <td> <%= contact.birthdate.strftime("%Y %B %d") unless contact.birthdate.nil? %> </td>
            <td> <%= contact.address %> </td>
            <td> <%= contact.email %> </td>
            <td> <%= contact.cc_franchise %> </td>
            <td> <%= contact.cc_mask %> </td>
        </tr>
    <% end %>
  </tbody>
</table>

<div class="flickr_pagination">
  <%= will_paginate @contacts, :container => false %>
</div>


<%= link_to 'Imported files', contacts_files_path, class: "btn btn-primary"%>